package frc.robot.subsystems;

import static edu.wpi.first.units.Units.*;

import java.io.IOException;
import java.lang.reflect.Field;
import java.util.Optional;
import java.util.function.Supplier;

import org.json.simple.parser.ParseException;

import com.ctre.phoenix6.SignalLogger;
import com.ctre.phoenix6.Utils;
import com.ctre.phoenix6.swerve.SwerveDrivetrainConstants;
import com.ctre.phoenix6.swerve.SwerveModuleConstants;
import com.ctre.phoenix6.swerve.SwerveRequest;
import com.pathplanner.lib.auto.AutoBuilder;
import com.pathplanner.lib.config.PIDConstants;
import com.pathplanner.lib.config.RobotConfig;
import com.pathplanner.lib.controllers.PPHolonomicDriveController;
import com.pathplanner.lib.path.PathConstraints;

import edu.wpi.first.math.MathUtil;
import edu.wpi.first.math.Matrix;
import edu.wpi.first.math.filter.LinearFilter;
import edu.wpi.first.math.geometry.Pose2d;
import edu.wpi.first.math.geometry.Rotation2d;
import edu.wpi.first.math.kinematics.ChassisSpeeds;
import edu.wpi.first.math.numbers.N1;
import edu.wpi.first.math.numbers.N3;
import edu.wpi.first.math.util.Units;
import edu.wpi.first.wpilibj.DriverStation;
import edu.wpi.first.wpilibj.DriverStation.Alliance;
import edu.wpi.first.wpilibj.Notifier;
import edu.wpi.first.wpilibj.RobotController;
import edu.wpi.first.wpilibj.smartdashboard.Field2d;
import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;
import edu.wpi.first.wpilibj2.command.Command;
import edu.wpi.first.wpilibj2.command.Commands;
import edu.wpi.first.wpilibj2.command.Subsystem;
import edu.wpi.first.wpilibj2.command.sysid.SysIdRoutine;
import frc.robot.Constants.PathPlannerConstants;
import frc.robot.Constants.PoseConstants;
import frc.robot.generated.TunerConstants.TunerSwerveDrivetrain;

/**
 * Class that extends the Phoenix 6 SwerveDrivetrain class and implements
 * Subsystem so it can easily be used in command-based projects.
 *
 * Generated by the 2026 Tuner X Swerve Project Generator
 * https://v6.docs.ctr-electronics.com/en/stable/docs/tuner/tuner-swerve/index.html
 */
public class CommandSwerveDrivetrain extends TunerSwerveDrivetrain implements Subsystem {
    private Field2d generalField = new Field2d();
    private Field2d targetField = new Field2d();
    private TurretSubsystem m_turret = new TurretSubsystem(this);

    private static final double kSimLoopPeriod = 0.004; // 4 ms
    private Notifier m_simNotifier = null;
    private double m_lastSimTime;
    private double angleToTarget = 0;
    private double[] targetPose = new double[2];
    private double lastRotationAngle = 0;
    private LinearFilter angularVelocityFilter = LinearFilter.movingAverage(5);

    private boolean isAllianceBlue = false;

    private PathConstraints pathFindingConstraints;

    /* Blue alliance sees forward as 0 degrees (toward red alliance wall) */
    private static final Rotation2d kBlueAlliancePerspectiveRotation = Rotation2d.kZero;
    /* Red alliance sees forward as 180 degrees (toward blue alliance wall) */
    private static final Rotation2d kRedAlliancePerspectiveRotation = Rotation2d.k180deg;
    /* Keep track if we've ever applied the operator perspective before or not */
    private boolean m_hasAppliedOperatorPerspective = false;

    /* Swerve requests to apply during SysId characterization */
    private final SwerveRequest.SysIdSwerveTranslation m_translationCharacterization = new SwerveRequest.SysIdSwerveTranslation();
    private final SwerveRequest.SysIdSwerveSteerGains m_steerCharacterization = new SwerveRequest.SysIdSwerveSteerGains();
    private final SwerveRequest.SysIdSwerveRotation m_rotationCharacterization = new SwerveRequest.SysIdSwerveRotation();

    /* SysId routine for characterizing translation. This is used to find PID gains for the drive motors. */
    private final SysIdRoutine m_sysIdRoutineTranslation = new SysIdRoutine(
        new SysIdRoutine.Config(
            null,        // Use default ramp rate (1 V/s)
            Volts.of(4), // Reduce dynamic step voltage to 4 V to prevent brownout
            null,        // Use default timeout (10 s)
            // Log state with SignalLogger class
            state -> SignalLogger.writeString("SysIdTranslation_State", state.toString())
        ),
        new SysIdRoutine.Mechanism(
            output -> setControl(m_translationCharacterization.withVolts(output)),
            null,
            this
        )
    );

    /* SysId routine for characterizing steer. This is used to find PID gains for the steer motors. */
    private final SysIdRoutine m_sysIdRoutineSteer = new SysIdRoutine(
        new SysIdRoutine.Config(
            null,        // Use default ramp rate (1 V/s)
            Volts.of(7), // Use dynamic voltage of 7 V
            null,        // Use default timeout (10 s)
            // Log state with SignalLogger class
            state -> SignalLogger.writeString("SysIdSteer_State", state.toString())
        ),
        new SysIdRoutine.Mechanism(
            volts -> setControl(m_steerCharacterization.withVolts(volts)),
            null,
            this
        )
    );

    /*
     * SysId routine for characterizing rotation.
     * This is used to find PID gains for the FieldCentricFacingAngle HeadingController.
     * See the documentation of SwerveRequest.SysIdSwerveRotation for info on importing the log to SysId.
     */
    private final SysIdRoutine m_sysIdRoutineRotation = new SysIdRoutine(
        new SysIdRoutine.Config(
            /* This is in radians per second², but SysId only supports "volts per second" */
            Volts.of(Math.PI / 6).per(Second),
            /* This is in radians per second, but SysId only supports "volts" */
            Volts.of(Math.PI),
            null, // Use default timeout (10 s)
            // Log state with SignalLogger class
            state -> SignalLogger.writeString("SysIdRotation_State", state.toString())
        ),
        new SysIdRoutine.Mechanism(
            output -> {
                /* output is actually radians per second, but SysId only supports "volts" */
                setControl(m_rotationCharacterization.withRotationalRate(output.in(Volts)));
                /* also log the requested output for SysId */
                SignalLogger.writeDouble("Rotational_Rate", output.in(Volts));
            },
            null,
            this
        )
    );

    /* The SysId routine to test */
    private SysIdRoutine m_sysIdRoutineToApply = m_sysIdRoutineTranslation;
    
    
    
        /**
         * Constructs a CTRE SwerveDrivetrain using the specified constants.
         * <p>
         * This constructs the underlying hardware devices, so users should not construct
         * the devices themselves. If they need the devices, they can access them through
         * getters in the classes.
         *
         * @param drivetrainConstants   Drivetrain-wide constants for the swerve drive
         * @param modules               Constants for each specific module
         */
        public CommandSwerveDrivetrain(
            SwerveDrivetrainConstants drivetrainConstants,
            SwerveModuleConstants<?, ?, ?>... modules
        ) {
            super(drivetrainConstants, modules);
            if (Utils.isSimulation()) {
                startSimThread();
            }
    
            configureAutoBuilder();
            SmartDashboard.putData("GeneralField", generalField);
            SmartDashboard.putData("Target Field", targetField);
        }
        
    
        /**
         * Constructs a CTRE SwerveDrivetrain using the specified constants.
         * <p>
         * This constructs the underlying hardware devices, so users should not construct
         * the devices themselves. If they need the devices, they can access them through
         * getters in the classes.
         *
         * @param drivetrainConstants     Drivetrain-wide constants for the swerve drive
         * @param odometryUpdateFrequency The frequency to run the odometry loop. If
         *                                unspecified or set to 0 Hz, this is 250 Hz on
         *                                CAN FD, and 100 Hz on CAN 2.0.
         * @param modules                 Constants for each specific module
         */
        public CommandSwerveDrivetrain(
            SwerveDrivetrainConstants drivetrainConstants,
            double odometryUpdateFrequency,
            SwerveModuleConstants<?, ?, ?>... modules

        ) {
            super(drivetrainConstants, odometryUpdateFrequency, modules);
            if (Utils.isSimulation()) {
                startSimThread();
            }
    
            configureAutoBuilder();
            SmartDashboard.putData("General Field", generalField);
            SmartDashboard.putData("Target Field", targetField);
        }
    
        /**
         * Constructs a CTRE SwerveDrivetrain using the specified constants.
         * <p>
         * This constructs the underlying hardware devices, so users should not construct
         * the devices themselves. If they need the devices, they can access them through
         * getters in the classes.
         *
         * @param drivetrainConstants       Drivetrain-wide constants for the swerve drive
         * @param odometryUpdateFrequency   The frequency to run the odometry loop. If
         *                                  unspecified or set to 0 Hz, this is 250 Hz on
         *                                  CAN FD, and 100 Hz on CAN 2.0.
         * @param odometryStandardDeviation The standard deviation for odometry calculation
         *                                  in the form [x, y, theta]ᵀ, with units in meters
         *                                  and radians
         * @param visionStandardDeviation   The standard deviation for vision calculation
         *                                  in the form [x, y, theta]ᵀ, with units in meters
         *                                  and radians
         * @param modules                   Constants for each specific module
         */
        public CommandSwerveDrivetrain(
            SwerveDrivetrainConstants drivetrainConstants,
            double odometryUpdateFrequency,
            Matrix<N3, N1> odometryStandardDeviation,
            Matrix<N3, N1> visionStandardDeviation,
            SwerveModuleConstants<?, ?, ?>... modules
        ) {
            super(drivetrainConstants, odometryUpdateFrequency, odometryStandardDeviation, visionStandardDeviation, modules);
            if (Utils.isSimulation()) {
                startSimThread();
            }
    
            configureAutoBuilder();
            SmartDashboard.putData("General Field", generalField);
            SmartDashboard.putData("Target Field", targetField);
        }
    
        /**
         * Returns a command that applies the specified control request to this swerve drivetrain.
         *
         * @param request Function returning the request to apply
         * @return Command to run
         */
        public Command applyRequest(Supplier<SwerveRequest> request) {
            return run(() -> this.setControl(request.get()));
        }
    
        /**
         * Runs the SysId Quasistatic test in the given direction for the routine
         * specified by {@link #m_sysIdRoutineToApply}.
         *
         * @param direction Direction of the SysId Quasistatic test
         * @return Command to run
         */
        public Command sysIdQuasistatic(SysIdRoutine.Direction direction) {
            return m_sysIdRoutineToApply.quasistatic(direction);
        }
    
        /**
         * Runs the SysId Dynamic test in the given direction for the routine
         * specified by {@link #m_sysIdRoutineToApply}.
         *
         * @param direction Direction of the SysId Dynamic test
         * @return Command to run
         */
        public Command sysIdDynamic(SysIdRoutine.Direction direction) {
            return m_sysIdRoutineToApply.dynamic(direction);
        }
    
        public void configureAutoBuilder() {
            RobotConfig config;
            final SwerveRequest.ApplyRobotSpeeds applyRobotSpeeds = new SwerveRequest.ApplyRobotSpeeds();
    
            try{
                config = RobotConfig.fromGUISettings();
    
                AutoBuilder.configure(
                () -> this.getState().Pose, // Robot pose supplier
                this::resetPose, // Method to reset odometry (will be called if your auto has a starting pose)
                () -> this.getState().Speeds, // ChassisSpeeds supplier. MUST BE ROBOT RELATIVE
                (speeds, feedforwards) -> setControl( 
                        applyRobotSpeeds.withSpeeds(speeds)
                            .withWheelForceFeedforwardsX(feedforwards.robotRelativeForcesXNewtons())
                            .withWheelForceFeedforwardsY(feedforwards.robotRelativeForcesYNewtons())
                    ), // Method that will drive the robot given ROBOT RELATIVE ChassisSpeeds. Also optionally outputs individual module feedforwards
                new PPHolonomicDriveController( // PPHolonomicController is the built in path following controller for holonomic drive trains
                        new PIDConstants(5.0, 0.0, 0.0), // Translation PID constants
                        new PIDConstants(5.0, 0.0, 0.0) // Rotation PID constants
                ),
                config, // The robot configuration
                () -> {
                  // Boolean supplier that controls when the path will be mirrored for the red alliance
                  // This will flip the path being followed to the red side of the field.
                  // THE ORIGIN WILL REMAIN ON THE BLUE SIDE
    
                  var alliance = DriverStation.getAlliance();
                  if (alliance.isPresent()) {
                    return alliance.get() == DriverStation.Alliance.Red;
                  }
                  return false;
                },
                this // Reference to this subsystem to set requirements
                );
            } catch (Exception e) {
                DriverStation.reportError("Failed to configure PathPlanner", e.getStackTrace());
            }
    
            // Configure AutoBuilder last   
            pathFindingConstraints = new PathConstraints(
            PathPlannerConstants.MAX_VELOCITY_MPS,
            PathPlannerConstants.MAX_ACCELERATION_MPS,
            PathPlannerConstants.MAX_ANGULAR_VELOCITY_RAD,
            PathPlannerConstants.MAX_ANGULAR_ACCELERATION_RAD,
            PathPlannerConstants.NOMINAL_VOLTAGE_VOLTS, 
            false
        );     
    }

    public Pose2d getPose2d(){
        return this.getState().Pose;
    }

    private double rawAngularVelocity(){
        double currentRotation = getPose2d().getRotation().getRadians();
        
        double angularVelocity = (currentRotation- lastRotationAngle) / 0.02;
        
        lastRotationAngle = currentRotation;

      
        return angularVelocity;
    }

    public double getFilteredAngularVelocity(){
        return angularVelocityFilter.calculate(rawAngularVelocity());
    }
    

    public double calculateAngleToFieldPosition(double targetX, double targetY) {
        try {
            double xRelativeToPosition = 0;
            double yRelativeToPosition = 0;

            double xRelativeToFieldOrigin = m_turret.calculateTurretFieldPositionX();
            double yRelativeToFieldOrigin = m_turret.calculateTurretFieldPositionY();

            xRelativeToPosition = xRelativeToFieldOrigin - targetX;
            yRelativeToPosition = yRelativeToFieldOrigin - targetY;

            SmartDashboard.putNumber("XRelativeToPos", xRelativeToPosition);
            SmartDashboard.putNumber("YRelativeToPos", yRelativeToPosition);
        
            angleToTarget = Math.atan(yRelativeToPosition/xRelativeToPosition);

            if(xRelativeToFieldOrigin > targetX) {
                angleToTarget += Math.PI;
            }
       
            return angleToTarget;
        } catch (Exception e) {
            e.printStackTrace(); 
       
            return angleToTarget;
        }
    }

    @Override
    public void periodic() {
    
        
        /*
         * Periodically try to apply the operator perspective.
         * If we haven't applied the operator perspective before, then we should apply it regardless of DS state.
         * This allows us to correct the perspective in case the robot code restarts mid-match.
         * Otherwise, only check and apply the operator perspective if the DS is disabled.
         * This ensures driving behavior doesn't change until an explicit disable event occurs during testing.
         */
        if (!m_hasAppliedOperatorPerspective || DriverStation.isDisabled()) {
            DriverStation.getAlliance().ifPresent(allianceColor -> {
                setOperatorPerspectiveForward(
                    allianceColor == Alliance.Red
                        ? kRedAlliancePerspectiveRotation
                        : kBlueAlliancePerspectiveRotation
                );
                m_hasAppliedOperatorPerspective = true;
            });
        }

        

        if(this.isAllianceBlue() && m_turret.calculateTurretFieldPositionX() < PoseConstants.BLUE_ALLIANCE_ZONE_X) {
            SmartDashboard.putString("Target", "Blue Alliance Hub");
            targetPose[0] = PoseConstants.BLUE_ALLIANCE_HUB_LOCATION[0];
            targetPose[1] = PoseConstants.BLUE_ALLIANCE_HUB_LOCATION[1];
        }
        else if(this.isAllianceRed() && m_turret.calculateTurretFieldPositionX() > PoseConstants.RED_ALLIANCE_ZONE_X) {
            SmartDashboard.putString("Target", "Red Alliance Hub");
            targetPose[0] = PoseConstants.RED_ALLIANCE_HUB_LOCATION[0];
            targetPose[1] = PoseConstants.RED_ALLIANCE_HUB_LOCATION[1];
        }
        else if(this.isAllianceBlue() && m_turret.calculateTurretFieldPositionX() > PoseConstants.BLUE_ALLIANCE_ZONE_X && m_turret.calculateTurretFieldPositionY() < PoseConstants.CENTER_FIELD_Y) {
            SmartDashboard.putString("Target", "Blue Alliance Right Corner");
            targetPose[0] = PoseConstants.BLUE_ALLIANCE_RIGHT_CORNER[0];
            targetPose[1] = PoseConstants.BLUE_ALLIANCE_RIGHT_CORNER[1];
        }
        else if(this.isAllianceBlue() && m_turret.calculateTurretFieldPositionX() > PoseConstants.BLUE_ALLIANCE_ZONE_X && m_turret.calculateTurretFieldPositionY() > PoseConstants.CENTER_FIELD_Y) {
            SmartDashboard.putString("Target", "Blue Alliance Left Corner");
            targetPose[0] = PoseConstants.BLUE_ALLIANCE_LEFT_CORNER[0];
            targetPose[1] = PoseConstants.BLUE_ALLIANCE_LEFT_CORNER[1];
        }
        else if(this.isAllianceRed() && m_turret.calculateTurretFieldPositionX() < PoseConstants.RED_ALLIANCE_ZONE_X && m_turret.calculateTurretFieldPositionY() > PoseConstants.CENTER_FIELD_Y){
            SmartDashboard.putString("Target", "Red Alliance Right Corner");
            targetPose[0] = PoseConstants.RED_ALLIANCE_RIGHT_CORNER[0];
            targetPose[1] = PoseConstants.RED_ALLIANCE_RIGHT_CORNER[1];
        }
        else if(this.isAllianceRed() && m_turret.calculateTurretFieldPositionX() < PoseConstants.RED_ALLIANCE_ZONE_X && m_turret.calculateTurretFieldPositionY() < PoseConstants.CENTER_FIELD_Y) {
            SmartDashboard.putString("Target", "Red Alliance Left Corner");
            targetPose[0] = PoseConstants.RED_ALLIANCE_LEFT_CORNER[0];
            targetPose[1] = PoseConstants.RED_ALLIANCE_LEFT_CORNER[1];
        }      

        calculateAngleToFieldPosition(targetPose[0], targetPose[1]);

        generalField.setRobotPose(getPose2d());
        targetField.setRobotPose(new Pose2d(targetPose[0], targetPose[1], new Rotation2d(angleToTarget)));
        SmartDashboard.putNumber("Angle to Target", Units.radiansToDegrees(angleToTarget));
        SmartDashboard.putNumber("Distance to Target", getDistanceToTarget());
    }

    private void startSimThread() {
        m_lastSimTime = Utils.getCurrentTimeSeconds();

        /* Run simulation at a faster rate so PID gains behave more reasonably */
        m_simNotifier = new Notifier(() -> {
            final double currentTime = Utils.getCurrentTimeSeconds();
            double deltaTime = currentTime - m_lastSimTime;
            m_lastSimTime = currentTime;

            /* use the measured time delta, get battery voltage from WPILib */
            updateSimState(deltaTime, RobotController.getBatteryVoltage());
        });
        m_simNotifier.startPeriodic(kSimLoopPeriod);
    }

    public Command pathfindToPose(Pose2d pose){
        return AutoBuilder.pathfindToPose(pose, pathFindingConstraints, 0);
    }

    public Command pathfindToShootPose() {
        
        var alliance = DriverStation.getAlliance();
        SmartDashboard.putString("Alliance", alliance.toString());
        if (alliance.get() == Alliance.Blue)
            return Commands.run(
                () -> AutoBuilder.pathfindToPose(PoseConstants.BLUE_SHOOT_POSE, pathFindingConstraints, 0))
            .onlyIf(() -> alliance.get() == Alliance.Blue);
        else if (alliance.get() == Alliance.Red)
            return Commands.run(
                () -> AutoBuilder.pathfindToPose(PoseConstants.RED_SHOOT_POSE, pathFindingConstraints, 0))
            .onlyIf(() -> alliance.get() == Alliance.Red);

        return Commands.none();
    }

    /**
     * Adds a vision measurement to the Kalman Filter. This will correct the odometry pose estimate
     * while still accounting for measurement noise.
     *
     * @param visionRobotPoseMeters The pose of the robot as measured by the vision camera.
     * @param timestampSeconds The timestamp of the vision measurement in seconds.
     */
    @Override
    public void addVisionMeasurement(Pose2d visionRobotPoseMeters, double timestampSeconds) {
        super.addVisionMeasurement(visionRobotPoseMeters, Utils.fpgaToCurrentTime(timestampSeconds));
    }

    /**
     * Adds a vision measurement to the Kalman Filter. This will correct the odometry pose estimate
     * while still accounting for measurement noise.
     * <p>
     * Note that the vision measurement standard deviations passed into this method
     * will continue to apply to future measurements until a subsequent call to
     * {@link #setVisionMeasurementStdDevs(Matrix)} or this method.
     *
     * @param visionRobotPoseMeters The pose of the robot as measured by the vision camera.
     * @param timestampSeconds The timestamp of the vision measurement in seconds.
     * @param visionMeasurementStdDevs Standard deviations of the vision pose measurement
     *     in the form [x, y, theta]ᵀ, with units in meters and radians.
     */
    @Override
    public void addVisionMeasurement(
        Pose2d visionRobotPoseMeters,
        double timestampSeconds,
        Matrix<N3, N1> visionMeasurementStdDevs
    ) {
        super.addVisionMeasurement(visionRobotPoseMeters, Utils.fpgaToCurrentTime(timestampSeconds), visionMeasurementStdDevs);
    }

    /**
     * Return the pose at a given timestamp, if the buffer is not empty.
     *
     * @param timestampSeconds The timestamp of the pose in seconds.
     * @return The pose at the given timestamp (or Optional.empty() if the buffer is empty).
     */
    @Override
    public Optional<Pose2d> samplePoseAt(double timestampSeconds) {
        return super.samplePoseAt(Utils.fpgaToCurrentTime(timestampSeconds));
    }

    public double getAngleToTarget() {
        return angleToTarget;
    }

    public double getDistanceToTarget() {
        double robotX = m_turret.calculateTurretFieldPositionX();
        double robotY = m_turret.calculateTurretFieldPositionY();

        double targetX = targetPose[0];
        double targetY = targetPose[1];

        double relativeX = robotX - targetX;
        double relativeY = robotY - targetY;

        double distance = Math.sqrt(relativeX * relativeX + relativeY * relativeY);
        return distance;
    }

    public boolean isAllianceBlue(){
        return DriverStation.getAlliance().orElse(Alliance.Red) == Alliance.Blue;
    }

    public boolean isAllianceRed() {
        return DriverStation.getAlliance().orElse(Alliance.Blue) == Alliance.Red;
    }

    
}
